### ISSUE TITLE
Type Definitions missing

### ISSUE THREAD

**Issue by Crisfole** [dependents/node-precinct#121]
I'm trying to use precinct from typescript, but it complains that:

> Could not find a declaration file for module 'precinct'.

~I think it'd be well worth adding some `jsdoc` style type definitions and distributing them.~ Since you already _have_ jsdoc style type definitions you should extract them and distribute them. The package.json can add a `types` field to point typescript at the right location.

**Comment by Crisfole** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by XhmikosR** [comment]
https://github.com/dependents/node-precinct/releases/tag/v12.0.2
