### ISSUE TITLE
Allow for plug and play detectives

### ISSUE THREAD

**Issue by mrjoelkemp** [dependents/node-precinct#17]
Consumer should be able to register new detectives for use.

`precinct.use(mySweetDetective, 'python');`

**Comment by mrjoelkemp** [comment]
This would avoid us bloating this factory – forcing libs to download detectives they don't want.

**Comment by joscha** [comment]
@mrjoelkemp how would you feel about making the current ones `peerDependencies` for now, so at least precinct won't need a bump with newer versions? Or alternatively I could give the pattern above a go, but I think precinct would need a major version bump (unless we want to keep the ones we have as a default, which kind of defeats the purpose)

**Comment by mrjoelkemp** [comment]
Hey @joscha! Good idea. I don't know that there's much of a need at the moment. I had grand plans for precinct (and its family of detectives) to increase the number of supported languages. If that were to happen, then the dependencies could get pretty heavy and fixing this issue would be more important.

The heaviness mattered to an editor plugin that started all of these modules (https://packagecontrol.io/packages/Dependents). Since Sublime Text doesn't do an npm install, I have to bundle all of the deps. With the point above around supporting a bunch more languages, that editor package would increasingly take longer to install. With a pick-and-choose detective system, I could have released more specific versions of the plugin (a web version, a java version, and more).

Unless downstream users of this package are complaining about the install time, I'm not sure it's worth the effort at the moment.

If you agree, I can close this issue.
