### ISSUE TITLE
Please add support for precss

### ISSUE THREAD

**Issue by grigorii-horos** [dependents/node-precinct#31]
Precss syntax for `@import` simmilar to sass

**Comment by mrjoelkemp** [comment]
Hey @horosgrisa! Thanks for contributing. Please see the notes that I added on https://github.com/dependents/node-dependency-tree/issues/57. The language `precss` would need to be added similar to pug/jade. Alternatively, if both the syntax and import resolution algorithm are the same as sass, we should be able to re-register the sass detective and resolver under a new precss extension.

Let me know what you think.
