### ISSUE TITLE
Dynamic Imports in ES6 module without export are not detected

### ISSUE THREAD

**Issue by WIStudent** [dependents/node-precinct#60]
I am using something like this to bootstrap a single-page application:

moduleA.js:
```js
(async () => {
  const {hello} = await import('./moduleB');
  hello();
})();
```
module:B.js
```js
export const hello = () => {
  console.log('Module B: hello');
};
```
precinct doesn't detect the dependency to moduleB.js
```js
const {paperwork} = require('precinct');
const deps = paperwork('./moduleA.js'));
console.log(`Deps A: ${deps}`);
```

If I add an export to moduleA, the dependecy will be detected:
```js
(async () => {
  const {hello} = await import('./moduleB');
  hello();
})();

export default undefined;
```

**Comment by WIStudent** [comment]
I figured out that it is node-ast-module-types that does not recognize a script with only dynamic imports as an es6 module. I opened a pull request there https://github.com/dependents/node-ast-module-types/pull/14

**Comment by mrjoelkemp** [comment]
@WIStudent thanks! You should be able to do a fresh install of this module (or whichever parent module you're using) to get that ast-module-types fix. Let me know if it doesn't work and there might be another change needed in another lib (maybe node-detective-es6).

**Comment by WIStudent** [comment]
It worked perfectly, thanks :)

**Comment by mrjoelkemp** [comment]
Woohoo! Great job.
