### ISSUE TITLE
Keep a changelog (at least for breaking changes)

### ISSUE THREAD

**Issue by voxpelli** [dependents/node-precinct#61]
It's fairly hard to know what one should look out for when upgrading from`5.x` to `6.x` when there are no notes about it anywhere – no changelog file, no tag notes, no release 🙂 

Some other arguments in favor of a changelog: https://keepachangelog.com/

If you feel it's too much work to keep a changelog for each and every version, then at least log the breaking changes so that it becomes easy to upgrade and tag along with new major versions. That way you will also help keeping as many users as possible on the newest version, which helps with possible contributions from others 🙂

**Comment by mrjoelkemp** [comment]
Hey! Thanks for the request.

I agree that more docs on changes are helpful. 

As a workaround, and what I've relied on is that the commit log of this repo (visible in the github ui) has all commits between tagged releases. The commits should be descriptive in terms of leaving hints at what has changed. Commits between major versions indicate that the commit was breaking. If someone wants to contribute tooling or manual work for generating changelogs, I'm open to reviewing a PR. 

Thanks again!
