### ISSUE TITLE
TypeScript file with a cast fails to find any dependencies

### ISSUE THREAD

**Issue by esprehn** [dependents/node-precinct#64]
#### example.ts
```ts
import React from 'react';

export default class Example extends React.Component<any, any> {
  render() { 
    console.log(this as any);
    return null;
  }
}

```

```
$ precinct ./example.ts 
[]
```

If you remove the `as any` cast then:

```
$ precinct ./example.ts 
[ 'react' ]
```

This means that precinct misses imports in any file using casts in a function call.

**Comment by lo1tuma** [comment]
I’ve encountered the same issue. Maybe this is because `detective-typescript` still uses [typescript v3 instead of v4](https://github.com/pahen/detective-typescript/issues/37).

**Comment by XhmikosR** [comment]
[v9.0.0](https://github.com/dependents/node-precinct/releases/tag/v9.0.0) is out which updates detective-typescript to use Typescript 4.x.
