### ISSUE TITLE
Missing `mixedImports` for TypeScript files

### ISSUE THREAD

**Issue by codemonkey800** [dependents/node-precinct#65]
Was trying to use `mixedImports` for my company's TypeScript project but I found it's not supported. It should be as simple as copying the following but for TypeScript:
https://github.com/dependents/node-precinct/blob/6eb6c276977dfe9f1ccfd086e28fe5ad35fb0200/index.js#L120-L122

**Comment by XhmikosR** [comment]
[v9.0.0](https://github.com/dependents/node-precinct/releases/tag/v9.0.0) is out which updates detective-typescript to use Typescript 4.x.
