### ISSUE TITLE
Export regular text instead of array in cli

### ISSUE THREAD

**Issue by fregante** [dependents/node-precinct#76]
CLI tools don't expect to receive input in the JavaScript array format, I don't know what to do with this, I'd have to parse it as JS:

```sh
$ precinct file.js
[ 'a', 'b' ]

````

bur rather it should just be a plain list:

```sh
$ precinct file.js
a
b
````

**Comment by mrjoelkemp** [comment]
Thanks for the report. Feel free to submit a PR.
